version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        BASE_URL: ${BASE_URL:-http://localhost:8080}
    container_name: insta-clone-prod
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/backend/storage
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - insta-clone-network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password
      APP_ENV: production
      APP_DEBUG: 'false'
      VITE_BASE_URL: ${VITE_BASE_URL:-http://localhost:8080}

  mysql:
    image: mysql:8.0-debian
    container_name: insta-clone-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - insta-clone-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:

networks:
  insta-clone-network:
    driver: bridge 